### ISSUE TITLE
kubeadm: preflight FQDN check

### ISSUE THREAD

**Issue by dmmcquay** [apprenda/kubernetes#11]
there are a variety of system configuration errors (such as cloud-init bugs when deploying on AWS) which can cause hostname and uname -n to be wrong for a given host. This will cause kubeadm setup to fail in interesting and hard-to-figure-out ways (it doesn't fail until you start trying to set up DNS on the master, for example).

This PR adds a preflight check to test whether or not the server can reach itself using that name. This does not catch the case that the FQDN belongs to a different but valid server, but it would catch some of the cases.

**Comment by pires** [comment]
Where's _this PR_?

**Comment by dmmcquay** [comment]
@pires https://github.com/kubernetes/kubernetes/pull/40771
