### ISSUE TITLE
kubeadm : add integration tests

### ISSUE THREAD

**Issue by dmmcquay** [apprenda/kubernetes#7]
On going work to increase tests for kubeadm code base, focusing on integration tests.

Current PRs open working on this are https://github.com/kubernetes/kubernetes/pull/40175 and https://github.com/kubernetes/kubernetes/pull/40045

**Comment by dmmcquay** [comment]
Waiting for review on kubernetes#40175

currently moved tests from `cmd/kubeadm/test` into `test/integration/kubeadm`

Although there is an argument that these are not integration tests, but 'command tests', so that we would actually have unit, cmd, integration, and e2e tests. This will have to be discussed in the SIG meeting.

**Comment by pires** [comment]
Blocked by #10.
