### ISSUE TITLE
kubeadm: add e2e tests

### ISSUE THREAD

**Issue by dmmcquay** [apprenda/kubernetes#8]
On going work to increase tests for kubeadm code base, focusing on e2e tests.

Work will either follow what is being done with kubernetes-anywhere + `hack/e2e.go` and syncing up with kubernetes test-infra, or working and building kubeadm specific e2e tests.  Would be built with https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md

**Comment by pires** [comment]
Blocked by #10.
