### ISSUE TITLE
Write SIG-cluster-lifecycle integration and e2e tests discussion Doc

### ISSUE THREAD

**Issue by dmmcquay** [apprenda/kubernetes#9]
Write document to discuss options for integration and e2e tests for kubeadm.  

Doc found here: https://docs.google.com/document/d/1d-xUyYe4DMjyV1-xB6xqn6FTiryN2FXnKa4JF1jKozc/edit#

**Comment by dmmcquay** [comment]
Waiting on review by @pires

**Comment by pires** [comment]
Done. Overall, LGTM just a few nits and a question.

Please, add it to the sig meeting agenda.

**Comment by dmmcquay** [comment]
Doc finished and added to agenda.
